name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  
jobs:
  build_wheel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
          
      - name: Build wheel
        run: |
          python -m pip install --user --upgrade build
          python -m build
          ls dist/*$(cat work/version)*.whl | xargs pip install
          # ./test3.py -f testdata/DOMAINS.txt # currently we have no whois cli
      - name: Test with rl-scanner
        run: |
          rm -rf report
          mkdir -p packages report
          cp dist/*$(cat work/version)*.whl packages
          docker run --pull always --rm \
            -u $(id -u):$(id -g) \
            -v "$(pwd)/packages:/packages:ro" \
            -v "$(pwd)/report:/report" \
            -e RLSECURE_ENCODED_LICENSE="${RL_DEPLOY_ENCODED_KEY}" \
            -e RLSECURE_SITE_KEY="${RL_DEPLOY_SITE_KEY}" \
            reversinglabs/rl-scanner \
            rl-scan \
                --package-path=/packages/whoisdomain*$(cat work/version)*.whl \
                --report-path=/report \
                --report-format=all

