name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  
jobs:
  build_wheel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
          
      - name: Build wheel
        run: |
          python -m pip install --user --upgrade build
          python -m build
          ls dist/*$(cat work/version)*.whl | xargs pip install
          # ./test3.py -f testdata/DOMAINS.txt # currently we have no whois cli
          
